#!/usr/bin/env node
if (!process.env.TOKEN) {
	console.log('Bot login token not found. Make sure you created a .env file and added: ');
	console.log('TOKEN=your token here');
	console.log(`Alternatively if you did the above, make sure you're starting the bot with npm start`);
	return;
}
console.log('Starting...');
require('module')._load('./dist/app.js', module, true);
