/** Declaration file generated by dts-gen */
declare module 'fuzzy-matching' {
export = FuzzyMatching;

class FuzzyMatching {
    constructor(items: any);

    add(item: any): any;

    get(item: any, criteria: any): any;
  }
}