BEGIN;

DROP TABLE IF EXISTS teamraters;
DROP TABLE IF EXISTS lines;
DROP TABLE IF EXISTS userlist;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS channellines;
DROP TABLE IF EXISTS channels;
DROP TABLE IF EXISTS servers;

COMMIT;
